### PR TITLE
Update and add migration for django 1.8

### PR DESCRIPTION
**Pull request by safwanrahman**
This change is actually made in [kitsune #2781](https://github.com/mozilla/kitsune/pull/2781) by @mythmon.
Hoping that, it will be merged in this project. @jlward what do you think?

### CODE REVIEW

**Comment by mythmon** [comment]
@safwanrahman one thing to watch out for: I changed some things in ways that are specif to Django 1.8 or Kitsune. For example, there are imports from kitsune here, and it no longer uses the django-authority fixtures. You'll need to fix that before this can be merged.

**Comment by safwanrahman** [comment]
Oh! Yeah. I did not notice that. Thanks. I will fix that

**Comment by safwanrahman** [comment]
@jezdez is it possible for you to review the PR?

**Comment by jezdez** [comment]
@safwanrahman Sorry, can't promise a code review of this due to time constraints

**Comment by jezdez** [comment]
@safwanrahman caught me on IRC and I took a quick look. This PR looks like three separate things at least:

1) lots of cosmetic code changes to match pep8 and a few other coventions, probably from kitsune being checked with flake8 or similar
2) a new initial migration for Django 1.8
3) some minor fixes for old versions of Django that aren't needed anymore

The actual commits mix up those things and should be separated into separate commits.

Since the tests currently don't pass please drop support for any Django < 1.8 since it's unsupported and Python 2.6 as well while you're at it. You can make that the fourth commit.

**Comment by safwanrahman** [comment]
updated @jezdez

**Comment by jezdez** [comment]
@safwanrahman Ah, apologies for not making myself clear, I meant it would be good to have separate commits for the points I listed in my last comment.

You could start by combining e341a83e034e98f410ccc63ec9ce85b88e483833 and 29f2b1a5d3cd58d61d6c5470fc497dd830e81730 and then extract the Django migration into an own commit just like the code that was there to support old Django versions. That could be combined with 9a528c941d6a76bf1fa20c5ae19420d649c84bf3.

**Comment by safwanrahman** [comment]
@jezdez updated. Can you please review it?

**Comment by bogdanpetrea** [comment]
Hey, can we have this please?

**Comment by jezdez** [comment]
nice!

**Pull request merged**
